# :asset_root: public
# :load_path:
#   - app/javascripts
#   - vendor/sprockets/*/src
#   - vendor/plugins/*/javascripts
#   - vendor/plugins/*/app/javascripts

javascripts_path: app/javascripts
javascripts_lib_path: app/javascripts/lib
javascripts_route: javascripts
